services:
  - docker

before_script:
    - docker run --rm -d -v `pwd`:/www/ --name wumvi.core.db wumvi/www.dev
    - docker exec wumvi.core.db composer install  --no-interaction --prefer-source --dev
script:
    - docker exec wumvi.core.db composer test

after_success:
    - bash <(curl -s https://codecov.io/bash)
